<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="126743" started-at="2020-01-19T01:01:15 GMT-06:00" finished-at="2020-01-19T01:03:22 GMT-06:00">
    <groups>
    </groups>
    <test name="Default test" duration-ms="126743" started-at="2020-01-19T01:01:15 GMT-06:00" finished-at="2020-01-19T01:03:22 GMT-06:00">
      <class name="com.demo.lms.TestCase.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="setUp" is-config="true" duration-ms="18751" started-at="2020-01-19T01:01:20 GMT-06:00" finished-at="2020-01-19T01:01:39 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="fbRegistrationTest(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="fbRegistrationTest" duration-ms="1627" started-at="2020-01-19T01:01:39 GMT-06:00" data-provider="data" finished-at="2020-01-19T01:01:40 GMT-06:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[rahul]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[rahul@7894]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[225]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook] but found [https://www.facebook.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook] but found [https://www.facebook.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.demo.lms.TestCase.HomePageTest.fbRegistrationTest(HomePageTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fbRegistrationTest -->
        <test-method status="PASS" signature="closeInstance()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="closeInstance" is-config="true" duration-ms="1" started-at="2020-01-19T01:01:42 GMT-06:00" finished-at="2020-01-19T01:01:42 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeInstance -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="setUp" is-config="true" duration-ms="24155" started-at="2020-01-19T01:01:42 GMT-06:00" finished-at="2020-01-19T01:02:06 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="fbRegistrationTest(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="fbRegistrationTest" duration-ms="571" started-at="2020-01-19T01:02:06 GMT-06:00" data-provider="data" finished-at="2020-01-19T01:02:06 GMT-06:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rahul]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[124.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[54]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook] but found [https://www.facebook.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook] but found [https://www.facebook.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.demo.lms.TestCase.HomePageTest.fbRegistrationTest(HomePageTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fbRegistrationTest -->
        <test-method status="PASS" signature="closeInstance()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="closeInstance" is-config="true" duration-ms="0" started-at="2020-01-19T01:02:07 GMT-06:00" finished-at="2020-01-19T01:02:07 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeInstance -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="setUp" is-config="true" duration-ms="31021" started-at="2020-01-19T01:02:07 GMT-06:00" finished-at="2020-01-19T01:02:38 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="fbRegistrationTest(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="fbRegistrationTest" duration-ms="788" started-at="2020-01-19T01:02:38 GMT-06:00" data-provider="data" finished-at="2020-01-19T01:02:38 GMT-06:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rahul]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[14012]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook] but found [https://www.facebook.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook] but found [https://www.facebook.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.demo.lms.TestCase.HomePageTest.fbRegistrationTest(HomePageTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fbRegistrationTest -->
        <test-method status="PASS" signature="closeInstance()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="closeInstance" is-config="true" duration-ms="1" started-at="2020-01-19T01:02:39 GMT-06:00" finished-at="2020-01-19T01:02:39 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeInstance -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="setUp" is-config="true" duration-ms="39400" started-at="2020-01-19T01:02:39 GMT-06:00" finished-at="2020-01-19T01:03:18 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="fbRegistrationTest(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="fbRegistrationTest" duration-ms="662" started-at="2020-01-19T01:03:18 GMT-06:00" data-provider="data" finished-at="2020-01-19T01:03:19 GMT-06:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[rahul@546]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rahul1412]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[555]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook] but found [https://www.facebook.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook] but found [https://www.facebook.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.demo.lms.TestCase.HomePageTest.fbRegistrationTest(HomePageTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fbRegistrationTest -->
        <test-method status="PASS" signature="closeInstance()[pri:0, instance:com.demo.lms.TestCase.HomePageTest@1efed156]" name="closeInstance" is-config="true" duration-ms="0" started-at="2020-01-19T01:03:22 GMT-06:00" finished-at="2020-01-19T01:03:22 GMT-06:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeInstance -->
      </class> <!-- com.demo.lms.TestCase.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
